[versions]
springBoot = "3.5.16"
springDependencyManagement = "1.1.7"
postgresql = "42.7.13"
h2 = "2.4.240"
flyway = "13.3.0"
hikari = "7.0.2"
slf4j = "2.0.17"
logback = "1.5.20"
junit = "5.14.4"
awaitility = "4.3.0"
assertj = "3.27.6"
testcontainers = "1.21.4"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
